spring:
  application:
    name: ORDER-SERVICE
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/orderdb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  tracing:
    enabled: true # Enabling distributed tracing
    sampling:
      probability: 1.0 # All requests sent by Postman will be traced
    propagation:
      type: b3 # B3 propagation format used by Zipkin

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans} # Zipkin endpoint

  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans, httptrace, prometheus

  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.tnf.order_service: DEBUG
    org.springframework.cloud.sleuth: DEBUG

info:
  app:
    name: Order Service
    version: 1.0.0
    description: Manages Orders